name: mkuhnt
favicon: null
layout_spectrum: 0.3030303716659546
typography_spectrum: 0.7295402635354549
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.38611176889389753
  lightness: 0.17278381530195475
  saturation: 0.6725034662522376
  rhythmicContrast: 0.9427330349572003
purpose: []
