favicon: null
name: mkuhnt
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.6664876
  brandStrength: 0.3861117688938975
  lightness: 0.7244898
  brandColors:
    - '#ffffff'
    - '#a3cdff'
    - '#080913'
    - '#d09f96'
    - '#973f47'
  rhythmicContrast: 0.7384533
typography_spectrum: 0.4892589
layout_spectrum: 0.7083781
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
